### ISSUE TITLE
Table votes

### ISSUE THREAD

**Issue by FCatalfamo** [DataAccess2020/Capstone_project_FC#1]
:rotating_light: Non riesco a effettuare la richiesta delle API dal sito ProPublica
Se qualcuno volesse fare un tentativo i pacchetti sono nel file 01_preparation e i dati nel file 05 votes table
Se necessitate dell'API key ve la mando in privato

**Comment by DeAngelisA** [comment]
@FCatalfamo: cosí ricevo la mail solo io. Scrivi l'issue nella repo [general info](https://github.com/DataAccess2020/general-info) e poi tagga tutti usando la @. Ti consiglio di mettere un po' di codice (poco e semplificato, solo la call) per dar modo agli altri di aiutarti.

**Comment by FCatalfamo** [comment]
Scaricati tutti

**Comment by DeAngelisA** [comment]
@FCatalfamo grande, sei un fenomeno!
